"""boshlangich sxema

Revision ID: ec3312949a85
Revises: 
Create Date: 2026-08-31 21:35:18.391797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec3312949a85'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('short_name', sa.String(length=120), nullable=False),
    sa.Column('publisher', sa.String(length=500), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.Column('issn', sa.String(length=9), nullable=True),
    sa.Column('eissn', sa.String(length=9), nullable=True),
    sa.Column('languages', sa.JSON(), nullable=False),
    sa.Column('oak_status', sa.String(length=20), nullable=False),
    sa.Column('access', sa.String(length=20), nullable=False),
    sa.Column('founded', sa.Integer(), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journals_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_journals_eissn'), ['eissn'], unique=False)
        batch_op.create_index(batch_op.f('ix_journals_issn'), ['issn'], unique=False)
        batch_op.create_index(batch_op.f('ix_journals_oak_status'), ['oak_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_journals_slug'), ['slug'], unique=True)

    op.create_table('oak_import_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('records_seen', sa.Integer(), nullable=False),
    sa.Column('registry_created', sa.Integer(), nullable=False),
    sa.Column('journals_created', sa.Integer(), nullable=False),
    sa.Column('journals_updated', sa.Integer(), nullable=False),
    sa.Column('source_sha256', sa.String(length=64), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('oak_import_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oak_import_runs_status'), ['status'], unique=False)

    op.create_table('oauth_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('redirect_to', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('oauth_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oauth_states_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_oauth_states_state'), ['state'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_subject', sa.String(length=200), nullable=False),
    sa.Column('orcid', sa.String(length=19), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('affiliation', sa.String(length=300), nullable=True),
    sa.Column('scholar_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_subject', name='user_provider_uq')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_is_admin'), ['is_admin'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_orcid'), ['orcid'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_provider'), ['provider'], unique=False)

    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journal_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('normalized_title', sa.Text(), nullable=False),
    sa.Column('authors', sa.JSON(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('language', sa.String(length=30), nullable=True),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.Column('publication_date', sa.String(length=80), nullable=True),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('volume', sa.String(length=80), nullable=True),
    sa.Column('issue', sa.String(length=80), nullable=True),
    sa.Column('pages', sa.String(length=80), nullable=True),
    sa.Column('doi', sa.String(length=300), nullable=True),
    sa.Column('landing_url', sa.Text(), nullable=True),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.Column('search_text', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('harvested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_articles_doi'), ['doi'], unique=True)
        batch_op.create_index(batch_op.f('ix_articles_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_journal_id'), ['journal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_normalized_title'), ['normalized_title'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_publication_date'), ['publication_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_publication_year'), ['publication_year'], unique=False)

    # Ifoda-indekslar: SQLAlchemy 2.0 SQLite'da ularni aks ettira olmaydi,
    # shuning uchun autogenerate o'tkazib yuboradi. Qo'lda yozamiz — ular
    # ro'yxat va jurnal sahifasining asosiy so'rovlarini tez saqlaydi.
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_articles_feed "
        "ON articles (is_deleted, publication_year DESC, id DESC)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_articles_journal_feed "
        "ON articles (journal_id, is_deleted, publication_year DESC, id DESC)"
    )

    op.create_table('audit_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journal_id', sa.Integer(), nullable=False),
    sa.Column('candidate_url', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('discovered_base_url', sa.Text(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('journal_id', 'candidate_url', name='audit_job_candidate_uq')
    )
    with op.batch_alter_table('audit_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_jobs_journal_id'), ['journal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_jobs_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_jobs_status'), ['status'], unique=False)

    op.create_table('editorial_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journal_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('role', sa.String(length=300), nullable=True),
    sa.Column('affiliation', sa.Text(), nullable=True),
    sa.Column('orcid', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('journal_id', 'name', 'role', name='editorial_member_uq')
    )
    with op.batch_alter_table('editorial_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_editorial_members_journal_id'), ['journal_id'], unique=False)

    op.create_table('harvest_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journal_id', sa.Integer(), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=False),
    sa.Column('metadata_prefix', sa.String(length=80), nullable=False),
    sa.Column('repository_name', sa.Text(), nullable=True),
    sa.Column('protocol_version', sa.String(length=30), nullable=True),
    sa.Column('datestamp_granularity', sa.String(length=50), nullable=True),
    sa.Column('deleted_record_policy', sa.String(length=30), nullable=True),
    sa.Column('available_formats', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('insecure_ssl', sa.Boolean(), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('journal_id', 'base_url', 'metadata_prefix', name='source_identity_uq')
    )
    with op.batch_alter_table('harvest_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_harvest_sources_journal_id'), ['journal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_harvest_sources_status'), ['status'], unique=False)

    op.create_table('journal_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journal_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('journal_id', 'kind', 'value', name='journal_contact_uq')
    )
    with op.batch_alter_table('journal_contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_contacts_journal_id'), ['journal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_contacts_kind'), ['kind'], unique=False)

    op.create_table('journal_indexing_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journal_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('claim_url', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('journal_id', 'provider', name='journal_indexing_claim_uq')
    )
    with op.batch_alter_table('journal_indexing_claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_indexing_claims_journal_id'), ['journal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_indexing_claims_provider'), ['provider'], unique=False)

    op.create_table('journal_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journal_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('journal_id', 'kind', 'url', name='journal_link_uq')
    )
    with op.batch_alter_table('journal_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_links_journal_id'), ['journal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_links_kind'), ['kind'], unique=False)

    op.create_table('journal_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journal_id', sa.Integer(), nullable=False),
    sa.Column('policy_type', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('journal_id', 'policy_type', name='journal_policy_uq')
    )
    with op.batch_alter_table('journal_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_policies_journal_id'), ['journal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_policies_policy_type'), ['policy_type'], unique=False)

    op.create_table('journal_profile_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journal_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('journal_id', 'field_name', name='journal_profile_field_uq')
    )
    with op.batch_alter_table('journal_profile_fields', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_profile_fields_field_name'), ['field_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_profile_fields_journal_id'), ['journal_id'], unique=False)

    op.create_table('journal_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journal_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('aims_scope', sa.Text(), nullable=True),
    sa.Column('peer_review', sa.Text(), nullable=True),
    sa.Column('publication_frequency', sa.Text(), nullable=True),
    sa.Column('submission_languages', sa.JSON(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('latest_issue', sa.Text(), nullable=True),
    sa.Column('completeness_score', sa.Float(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_profiles_journal_id'), ['journal_id'], unique=True)

    op.create_table('journal_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journal_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('journal_id', 'name', name='journal_section_uq')
    )
    with op.batch_alter_table('journal_sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_sections_journal_id'), ['journal_id'], unique=False)

    op.create_table('oak_registry_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_run_id', sa.Integer(), nullable=False),
    sa.Column('journal_id', sa.Integer(), nullable=True),
    sa.Column('source_key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('place', sa.Text(), nullable=True),
    sa.Column('organization', sa.Text(), nullable=True),
    sa.Column('specialty_code', sa.Text(), nullable=True),
    sa.Column('area', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('kind', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('added', sa.Text(), nullable=True),
    sa.Column('year', sa.Text(), nullable=True),
    sa.Column('removed', sa.Text(), nullable=True),
    sa.Column('decision', sa.Text(), nullable=True),
    sa.Column('source_reference', sa.Text(), nullable=True),
    sa.Column('link', sa.Text(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['import_run_id'], ['oak_import_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('oak_registry_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oak_registry_entries_area'), ['area'], unique=False)
        batch_op.create_index(batch_op.f('ix_oak_registry_entries_import_run_id'), ['import_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_oak_registry_entries_journal_id'), ['journal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_oak_registry_entries_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_oak_registry_entries_source_key'), ['source_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_oak_registry_entries_status'), ['status'], unique=False)

    op.create_table('oak_registry_snapshot_meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_run_id', sa.Integer(), nullable=False),
    sa.Column('publication_count', sa.Integer(), nullable=False),
    sa.Column('raw_row_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['import_run_id'], ['oak_import_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('oak_registry_snapshot_meta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oak_registry_snapshot_meta_import_run_id'), ['import_run_id'], unique=True)

    op.create_table('profile_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journal_id', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('completeness_score', sa.Float(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('journal_id', name='profile_job_journal_uq')
    )
    with op.batch_alter_table('profile_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profile_jobs_journal_id'), ['journal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_profile_jobs_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_profile_jobs_status'), ['status'], unique=False)

    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_sessions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_sessions_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('harvest_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('records_seen', sa.Integer(), nullable=False),
    sa.Column('records_created', sa.Integer(), nullable=False),
    sa.Column('records_updated', sa.Integer(), nullable=False),
    sa.Column('records_deleted', sa.Integer(), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['harvest_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('harvest_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_harvest_runs_source_id'), ['source_id'], unique=False)

    op.create_table('oak_registry_snapshot_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_run_id', sa.Integer(), nullable=False),
    sa.Column('registry_entry_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['import_run_id'], ['oak_import_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registry_entry_id'], ['oak_registry_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('import_run_id', 'registry_entry_id', name='oak_snapshot_entry_uq')
    )
    with op.batch_alter_table('oak_registry_snapshot_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oak_registry_snapshot_entries_import_run_id'), ['import_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_oak_registry_snapshot_entries_registry_entry_id'), ['registry_entry_id'], unique=False)

    op.create_table('source_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('oai_identifier', sa.Text(), nullable=False),
    sa.Column('oai_datestamp', sa.String(length=50), nullable=True),
    sa.Column('set_specs', sa.JSON(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('metadata_hash', sa.String(length=64), nullable=True),
    sa.Column('raw_xml', sa.Text(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['harvest_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'oai_identifier', name='source_record_identifier_uq')
    )
    with op.batch_alter_table('source_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_records_article_id'), ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_records_source_id'), ['source_id'], unique=False)

    op.create_table('user_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'article_id', name='user_article_uq')
    )
    with op.batch_alter_table('user_articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_articles_article_id'), ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_articles_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_articles_journal_feed")
    op.execute("DROP INDEX IF EXISTS ix_articles_feed")
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_articles_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_articles_article_id'))

    op.drop_table('user_articles')
    with op.batch_alter_table('source_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_records_source_id'))
        batch_op.drop_index(batch_op.f('ix_source_records_article_id'))

    op.drop_table('source_records')
    with op.batch_alter_table('oak_registry_snapshot_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oak_registry_snapshot_entries_registry_entry_id'))
        batch_op.drop_index(batch_op.f('ix_oak_registry_snapshot_entries_import_run_id'))

    op.drop_table('oak_registry_snapshot_entries')
    with op.batch_alter_table('harvest_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_harvest_runs_source_id'))

    op.drop_table('harvest_runs')
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_sessions_token_hash'))
        batch_op.drop_index(batch_op.f('ix_user_sessions_expires_at'))

    op.drop_table('user_sessions')
    with op.batch_alter_table('profile_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profile_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_profile_jobs_priority'))
        batch_op.drop_index(batch_op.f('ix_profile_jobs_journal_id'))

    op.drop_table('profile_jobs')
    with op.batch_alter_table('oak_registry_snapshot_meta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oak_registry_snapshot_meta_import_run_id'))

    op.drop_table('oak_registry_snapshot_meta')
    with op.batch_alter_table('oak_registry_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oak_registry_entries_status'))
        batch_op.drop_index(batch_op.f('ix_oak_registry_entries_source_key'))
        batch_op.drop_index(batch_op.f('ix_oak_registry_entries_kind'))
        batch_op.drop_index(batch_op.f('ix_oak_registry_entries_journal_id'))
        batch_op.drop_index(batch_op.f('ix_oak_registry_entries_import_run_id'))
        batch_op.drop_index(batch_op.f('ix_oak_registry_entries_area'))

    op.drop_table('oak_registry_entries')
    with op.batch_alter_table('journal_sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_sections_journal_id'))

    op.drop_table('journal_sections')
    with op.batch_alter_table('journal_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_profiles_journal_id'))

    op.drop_table('journal_profiles')
    with op.batch_alter_table('journal_profile_fields', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_profile_fields_journal_id'))
        batch_op.drop_index(batch_op.f('ix_journal_profile_fields_field_name'))

    op.drop_table('journal_profile_fields')
    with op.batch_alter_table('journal_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_policies_policy_type'))
        batch_op.drop_index(batch_op.f('ix_journal_policies_journal_id'))

    op.drop_table('journal_policies')
    with op.batch_alter_table('journal_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_links_kind'))
        batch_op.drop_index(batch_op.f('ix_journal_links_journal_id'))

    op.drop_table('journal_links')
    with op.batch_alter_table('journal_indexing_claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_indexing_claims_provider'))
        batch_op.drop_index(batch_op.f('ix_journal_indexing_claims_journal_id'))

    op.drop_table('journal_indexing_claims')
    with op.batch_alter_table('journal_contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_contacts_kind'))
        batch_op.drop_index(batch_op.f('ix_journal_contacts_journal_id'))

    op.drop_table('journal_contacts')
    with op.batch_alter_table('harvest_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_harvest_sources_status'))
        batch_op.drop_index(batch_op.f('ix_harvest_sources_journal_id'))

    op.drop_table('harvest_sources')
    with op.batch_alter_table('editorial_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_editorial_members_journal_id'))

    op.drop_table('editorial_members')
    with op.batch_alter_table('audit_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_audit_jobs_priority'))
        batch_op.drop_index(batch_op.f('ix_audit_jobs_journal_id'))

    op.drop_table('audit_jobs')
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_articles_publication_year'))
        batch_op.drop_index(batch_op.f('ix_articles_publication_date'))
        batch_op.drop_index(batch_op.f('ix_articles_normalized_title'))
        batch_op.drop_index(batch_op.f('ix_articles_journal_id'))
        batch_op.drop_index(batch_op.f('ix_articles_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_articles_doi'))

    op.drop_table('articles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_provider'))
        batch_op.drop_index(batch_op.f('ix_users_orcid'))
        batch_op.drop_index(batch_op.f('ix_users_is_admin'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('oauth_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauth_states_state'))
        batch_op.drop_index(batch_op.f('ix_oauth_states_created_at'))

    op.drop_table('oauth_states')
    with op.batch_alter_table('oak_import_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oak_import_runs_status'))

    op.drop_table('oak_import_runs')
    with op.batch_alter_table('journals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journals_slug'))
        batch_op.drop_index(batch_op.f('ix_journals_oak_status'))
        batch_op.drop_index(batch_op.f('ix_journals_issn'))
        batch_op.drop_index(batch_op.f('ix_journals_eissn'))
        batch_op.drop_index(batch_op.f('ix_journals_city'))

    op.drop_table('journals')
    # ### end Alembic commands ###
