import type { Article, Journal } from "./types";

export const journals: Journal[] = [
  {
    id: "fardu-ilmiy-xabarlari",
    name: "FarDU ilmiy xabarlari",
    shortName: "FarDU IX",
    publisher: "Farg‘ona davlat universiteti",
    city: "Farg‘ona",
    fields: ["Filologiya", "Pedagogika", "Tarix", "Biologiya"],
    issn: "2010-8419",
    eissn: "2181-1571",
    languages: ["O‘zbek", "Rus", "Ingliz"],
    oakStatus: "active",
    access: "open",
    oaiStatus: "healthy",
    oaiLastSync: "Bugun, 06:12",
    oaiBaseUrl: "https://journal.example.uz/oai",
    articleCount: 1555,
    issueCount: 88,
    founded: 1995,
    website: "https://journal.fdu.uz/",
    description:
      "Ko‘p tarmoqli ilmiy jurnal. Tabiiy, ijtimoiy va gumanitar fanlar bo‘yicha tadqiqotlarni nashr etadi.",
  },
  {
    id: "acta-camu",
    name: "Acta CAMU",
    shortName: "ACTA CAMU",
    publisher: "Central Asian Medical University",
    city: "Farg‘ona",
    fields: ["Tibbiyot"],
    issn: "2992-9024",
    languages: ["Ingliz", "Rus"],
    oakStatus: "active",
    access: "open",
    oaiStatus: "healthy",
    oaiLastSync: "Bugun, 05:48",
    oaiBaseUrl: "https://journal.example.uz/index.php/camu/oai",
    articleCount: 268,
    issueCount: 14,
    founded: 2022,
    website: "https://www.camuf.uz/en",
    description:
      "Klinik tibbiyot, profilaktika va zamonaviy tibbiy ta’lim yo‘nalishlaridagi tadqiqotlar jurnali.",
  },
  {
    id: "agro-ilm",
    name: "Agro ILM",
    shortName: "Agro ILM",
    publisher: "O‘zbekiston qishloq xo‘jaligi jurnali ilmiy ilovasi",
    city: "Toshkent",
    fields: ["Qishloq xo‘jaligi", "Texnika"],
    issn: "2091-5616",
    languages: ["O‘zbek", "Rus"],
    oakStatus: "active",
    access: "open",
    oaiStatus: "warning",
    oaiLastSync: "Kecha, 23:10",
    oaiBaseUrl: "https://qxjurnal.uz/index.php/ai/oai",
    articleCount: 892,
    issueCount: 61,
    founded: 2007,
    website: "https://qxjurnal.uz/index.php/ai",
    description:
      "Agronomiya, suv xo‘jaligi, agrotexnologiya va qishloq xo‘jaligi mexanizatsiyasi bo‘yicha ilmiy nashr.",
  },
  {
    id: "adabiy-meros",
    name: "Adabiy meros",
    shortName: "Adabiy meros",
    publisher: "Alisher Navoiy nomidagi Davlat adabiyot muzeyi",
    city: "Toshkent",
    fields: ["Filologiya"],
    issn: "2181-1320",
    languages: ["O‘zbek", "Rus"],
    oakStatus: "active",
    access: "mixed",
    oaiStatus: "missing",
    articleCount: 0,
    issueCount: 0,
    founded: 1968,
    website: "https://navoimuseum.uz/uz/jurnallar",
    description:
      "O‘zbek mumtoz va zamonaviy adabiyoti, matnshunoslik hamda adabiy manbashunoslik masalalariga bag‘ishlangan nashr.",
  },
  {
    id: "agro-inform",
    name: "Agro Inform",
    shortName: "Agro Inform",
    publisher: "Toshkent davlat agrar universiteti",
    city: "Toshkent",
    fields: ["Qishloq xo‘jaligi"],
    issn: "2181-8369",
    languages: ["O‘zbek", "Ingliz", "Rus"],
    oakStatus: "active",
    access: "open",
    oaiStatus: "healthy",
    oaiLastSync: "Bugun, 04:31",
    oaiBaseUrl: "https://agro-inform.uz/index.php/agro-inform/oai",
    articleCount: 431,
    issueCount: 25,
    founded: 2020,
    website: "https://agro-inform.uz/index.php/agro-inform",
    description:
      "Qishloq xo‘jaligi, oziq-ovqat xavfsizligi va agrar iqtisodiyotga oid ochiq ilmiy jurnal.",
  },
  {
    id: "qardu-xabarlari",
    name: "QarDU xabarlari",
    shortName: "QarDU xabarlari",
    publisher: "Qarshi davlat universiteti",
    city: "Qarshi",
    fields: ["Pedagogika", "Tarix", "Filologiya"],
    issn: "2181-0958",
    languages: ["O‘zbek", "Rus", "Ingliz"],
    oakStatus: "active",
    access: "open",
    oaiStatus: "warning",
    oaiLastSync: "2 kun oldin",
    articleCount: 712,
    issueCount: 39,
    founded: 2009,
    website: "https://qarshidu.uz/",
    description:
      "Ijtimoiy-gumanitar va tabiiy fanlar bo‘yicha universitet ilmiy axborotnomasi.",
  },
];

export const articles: Article[] = [
  {
    id: "a1",
    title: "Oliy ta’limda raqamli pedagogikaning yangi yondashuvlari",
    authors: ["Dilnoza Karimova", "Jasur Ergashev"],
    journalId: "fardu-ilmiy-xabarlari",
    year: 2026,
    volume: "7",
    issue: "4",
    pages: "44–52",
    language: "O‘zbek",
    fields: ["Pedagogika"],
    abstract:
      "Tadqiqot oliy ta’limda raqamli vositalardan foydalanish amaliyoti va uning ta’lim natijalariga ta’sirini tahlil qiladi.",
    keywords: ["raqamli pedagogika", "oliy ta’lim", "ta’lim texnologiyalari"],
    doi: "10.0000/demo.2026.041",
    hasPdf: true,
    harvestedAt: "2026-08-26T06:12:00Z",
    isDemo: true,
  },
  {
    id: "a2",
    title: "Clinical indicators in early cardiovascular risk assessment",
    authors: ["M. Rakhimov", "S. Yuldasheva", "A. Kim"],
    journalId: "acta-camu",
    year: 2026,
    volume: "4",
    issue: "2",
    pages: "18–27",
    language: "Ingliz",
    fields: ["Tibbiyot"],
    abstract:
      "This study evaluates a set of accessible clinical indicators for early cardiovascular risk stratification.",
    keywords: ["cardiovascular risk", "screening", "clinical indicators"],
    doi: "10.0000/demo.2026.118",
    hasPdf: true,
    harvestedAt: "2026-08-26T05:48:00Z",
    isDemo: true,
  },
  {
    id: "a3",
    title: "Tomchilatib sug‘orishda suv sarfini optimallashtirish usullari",
    authors: ["Akmal Xolmatov", "Feruza Sodiqova"],
    journalId: "agro-ilm",
    year: 2026,
    volume: "3",
    issue: "2",
    pages: "71–76",
    language: "O‘zbek",
    fields: ["Qishloq xo‘jaligi", "Texnika"],
    abstract:
      "Maqolada tomchilatib sug‘orish tizimlarida suv sarfini boshqarish va dala sharoitidagi kuzatuv natijalari yoritilgan.",
    keywords: ["tomchilatib sug‘orish", "suv tejamkorligi", "agrotexnologiya"],
    hasPdf: true,
    harvestedAt: "2026-08-25T23:10:00Z",
    isDemo: true,
  },
  {
    id: "a4",
    title: "Mumtoz she’riyat matnlarida muallif uslubining ifodalanishi",
    authors: ["Gulbahor Hamroyeva"],
    journalId: "fardu-ilmiy-xabarlari",
    year: 2026,
    volume: "7",
    issue: "4",
    pages: "103–111",
    language: "O‘zbek",
    fields: ["Filologiya"],
    abstract:
      "Mumtoz she’riyat namunalarida muallif uslubini yuzaga chiqaruvchi leksik va poetik birliklar qiyosiy o‘rganiladi.",
    keywords: ["mumtoz adabiyot", "poetika", "muallif uslubi"],
    hasPdf: true,
    harvestedAt: "2026-08-26T06:12:00Z",
    isDemo: true,
  },
  {
    id: "a5",
    title: "Tuproq sho‘rlanishini masofadan baholash imkoniyatlari",
    authors: ["Sardor Mamatqulov", "Lola Abdullayeva"],
    journalId: "agro-inform",
    year: 2026,
    volume: "6",
    issue: "3",
    pages: "29–38",
    language: "O‘zbek",
    fields: ["Qishloq xo‘jaligi"],
    abstract:
      "Sun’iy yo‘ldosh tasvirlari asosida sug‘oriladigan maydonlarda tuproq sho‘rlanishini baholash yondashuvi taklif etiladi.",
    keywords: ["tuproq", "sho‘rlanish", "masofadan zondlash"],
    doi: "10.0000/demo.2026.207",
    hasPdf: false,
    harvestedAt: "2026-08-26T04:31:00Z",
    isDemo: true,
  },
  {
    id: "a6",
    title: "Janubiy O‘zbekiston shaharlari tarixiy topografiyasi",
    authors: ["Baxtiyor Eshonqulov"],
    journalId: "qardu-xabarlari",
    year: 2025,
    volume: "2",
    issue: "4",
    pages: "88–97",
    language: "O‘zbek",
    fields: ["Tarix"],
    abstract:
      "Arxeologik va yozma manbalar asosida Janubiy O‘zbekiston shaharlari tarixiy topografiyasining ayrim jihatlari yoritiladi.",
    keywords: ["tarixiy topografiya", "shahar", "manbashunoslik"],
    hasPdf: true,
    harvestedAt: "2026-08-24T11:20:00Z",
    isDemo: true,
  },
];
